Tags: #Topic #TODO 

# Inductor

Inductors are elements in a circuit that resist changes in current by generating E-field that opposes the direction of the current.

Usually inductors appear as solenoids, which generates a B-field and then an opposing E-field at the center of the solenoid.

**Self Induction** - The act of an inductor generating an emf that opposes the flow of current.

**Back Emf** - Also called **"Self Induced Emf,"** this is the E-field generated by inductor to 

